# Uso de pandas

In [1]:
import pandas as pd
import numpy as np

## Funciones

df = dataframe (marco de datos)
read_cvs(path)

Podemos leer archivos cvs - xlsx

Un marco de datos o trabajo se compone de columnas (acostados) y filas (parados)

Podemos crear un dataframe apartir de un diccionario


In [5]:
diccionario = {
    "lenguajes": ["python", "java", "c++"],
    "nivel_conocimiento": ["básico", "intermedio", "avanzado"],
    "años_experiencia": [1, 3, 5]
}

Las claves son las columnas y los valores las filas

In [ ]:
# Crear un DataFrame a partir de un diccionario
df = pd.DataFrame(diccionario)
print(df)

In [ ]:
# Podemos obtener información de las columnas
get_lenguajes = df["lenguajes"]
print(get_lenguajes)

Para acceder podemos usar el metodo iloc que recibe como parametros los indices


In [ ]:
primer_elemento_columna_fila = df.iloc[0,0] #el primer parametro es la fila y el segundo la columna
print(primer_elemento_columna_fila)

Tambien tenemos el metodo loc que escribimos la columna deseada y la fila la seleccionamos con el indice.

In [ ]:
segundo_elemento_columna_fila = df.loc[1,"nivel_conocimiento"]
print(segundo_elemento_columna_fila)

# Trabar y Guardar con Pandas

si tenemos una columna seleccionada, podemos aplicar el metodo **unique** para obtener todos los valores unicos (que se repiten dos o mas veces)

Podemos guardar un marco de trabajo usando el metodo: **to_cvs("path.cvs)**

## Practica

In [4]:
data = {
    "folios": [1, 2, 3, 4, 5],
    "total": [100, 200, 300, 400, 500],
    "factuado": [True, False, True, False, True]
}

In [5]:
# Guardar los datos en un DataFrame
df = pd.DataFrame(data)

In [6]:
# Generar el archivo CSV
df.to_csv("data.csv")

In [ ]:
# Obtener el total de la columna "total"
total = df["total"].sum()
print(df["total"])
print(total)

In [ ]:
# Obtener solo los folios que no estan facturados
no_facturados = df[df["factuado"] == False]
print(no_facturados)

In [ ]:
# Obtener los folios facturados
facturados = df[df["factuado"] == True]
print(facturados)

In [ ]:
# Guardar los datos en un archivo CSV (facturados)
facturado = df[df["factuado"] == True]
# Quitar la columna "facturado"
facturado = facturado[["folios", "total"]]
print(facturado)
facturado.to_csv("Formato_Facturado.csv")

# Trabajar con NumPy


In [11]:
import numpy as np

# Crear un array en numpy
a = np.array([1, 2, 3, 4, 5])

# Ver el tipo de dato
type(a)
print(a.dtype) # <- Esto obtiene el tipo de dato de los elementos del array

# Numero de elementos en la matriz
print(a.size)

# Numero de dimensiones (listas)
print(a.ndim)

# Slicing

# Cambiar el valor de un elemento
b = np.array([1, 2, 3, 4, 5])
print(b)
b[0] = 10
print(b)

c = b[1:4]
print(c)

c[0:3]= 20,30,40
print(c)



int64
5
1
[1 2 3 4 5]
[10  2  3  4  5]
[2 3 4]
[20 30 40]


## Adición de vectores
Es una combinacion lineal que es el resultado de sumar 2 vectores

vector = v1+v2

**Multiplicacion**
vector = v1*v2

**Escalado (raiz)**
vector = 2*v1

**Producto punto (dot product)**
Se multiplican los primeros componentes de los vectores y luego sumamos la multiplicacion del segundo
El resultado repesenta que tan **similares** son los vectores

resultado = np.dot(v1,v2)


## Funciones globales

### Promedio de los vectores
promedio = vector.mean()

### Valor maximo
maximo = vector.max()

### Valor de pi
np.pi

### Funciones sin
y = np.sin(vector)




# Array attributes
print(arr_2d.ndim)  # ndim : Represents the number of dimensions or "rank" of the array.
# output : 2
print(arr_2d.shape)  # shape : Returns a tuple indicating the number of rows and columns in the array.
# Output : (3, 3)
print(arr_2d.size) # size: Provides the total number of elements in the array.
# Output : 9